services:
  txs-flower:
    image: 0xsambtc/safe-transaction-service:${TXS_VERSION}
    env_file:
      - container_env_files/txs.env
    depends_on:
      - txs-db
      - txs-redis
    command: docker/web/celery/flower/run.sh
    ports:
      - "5555:5555"
